### ISSUE TITLE
AttributeError with older pygame versions

### ISSUE THREAD

**Issue by Dimi20cen** [sugarlabs/sugargame#16]
The following pygame constants cause AttributeError
- pygame.K_PERCENT
- pygame.K_CURRENCYUNIT
- pygame.K_CURRENCYSUBUNIT
- pygame.K_AC_BACK
```
Traceback (most recent call last):
  File "/usr/bin/sugar-activity3", line 5, in <module>
    activityinstance.main()
  File "/usr/lib/python3.7/dist-packages/sugar3/activity/activityinstance.py", line 179, in main
    module = __import__(module_name)
  File "/home/dim/Activities/2-cars-activity/activity.py", line 12, in <module>
    import sugargame.canvas
  File "/home/dim/Activities/2-cars-activity/sugargame/canvas.py", line 28, in <module>
    import sugargame.event as event
  File "/home/dim/Activities/2-cars-activity/sugargame/event.py", line 35, in <module>
    class Translator(object):
  File "/home/dim/Activities/2-cars-activity/sugargame/event.py", line 78, in Translator
    pygame.K_PERCENT,
AttributeError: module 'pygame' has no attribute 'K_PERCENT'
```

Tested with pygame 1.9.4.post1.

**Comment by Dimi20cen** [comment]
Per chimosky,
- The way our release cycle works is that an activity should have the latest of it's dependencies at the time of the last release so it won't be a problem, and in most of the activities that require pygame2, the readme specifies that and a system wide update would also get them the latest pygame.

So this issue, is not really an issue, closing.
